before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: IHC99alRivVujg7KQwOqxdTRyWbfN22mknqDMQDt1pS1MZEcYOGKX5Xwg9EA1Nc/7CDb+D2s5yy88vDJU9DkInOfQK+rdVj8lDpnMVjkHgKtj9/iHFFZ0TjnuGOYKEaldmRRWb2ivnnt0+dJDxxdhBJCgcZ5lOdC5vl5FzhwiGwNpaq6UCLe6k1jdMxyOAi9DbXPETlB6AQzOFnmjdaW2MRddh+CD+KMedsE2lm0/yRY8XAppbjhecvuUeJ9pL1Ivz1qoyL/us119q9fjyxgPIU4F/oJ2Zmqet8eLKdpcjZkqNwgY/UW6W9AicPeP0Gb/6mSOk4PK1pDHfU9sUVIPu4a8c8uhh2FmKaW0uPQL/LVUvIHnIVxiZhpm2tLy5+8gxMrypSQ/yWVv7bNYkx+PfAHVOq5eLGtIKBirJYedpd8ZYZ6uNe30QC859ctc41SUNn64gycaVB6UciSIV8Z9Bc5Z9f7TK3nAxA/Z2z/EfIEy8yl2Zyh/hjflo0JQmtpGTc6B+snq1H9hSVPTVcW4YBBDBljafBhrvt5P6GZqt678szEOG+dMHhPyQf+df9+zb5eKrNSaI8DPX1fXmi49YObaTo+oS9UwWmnZ8GTxobN9IYFrqpYbxqpUSn4fu3cyf9hT9UNACVFgrLlhyMChQmCg+v45LaIZ0sg8s5Znlw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
